name: jj_pcparts_proj
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

#
environment:
  sdk: '>=3.3.3 <4.0.0'

#
dependencies:
  flutter:
    sdk: flutter

#
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  provider: ^6.1.2
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_storage: ^11.7.6
  flutter_native_splash: ^2.4.0
  material_design_icons_flutter: ^7.0.7296
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

#
  flutter_lints: ^4.0.0

#
flutter:
  uses-material-design: true
  assets:
    - assets/icons/jjpcparts_applogo.png
    - assets/icons/motherboard.png
    - assets/icons/case.png
    - assets/icons/gpu.png
    - assets/icons/monitor.png
    - assets/icons/mouse.png
    - assets/icons/cpu.png
    - assets/icons/psu.png
    - assets/icons/ram.png
    - assets/icons/ssd-drive.png
