// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArW-bEU1W32VoQw6JpQ7XXQl_kW01pGqM',
    appId: '1:232668855467:web:c91304acb829aa29d18bee',
    messagingSenderId: '232668855467',
    projectId: 'jjpcparts',
    authDomain: 'jjpcparts.firebaseapp.com',
    storageBucket: 'jjpcparts.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8IUuxE2K6R99i37Ph7UgxF3gPNm7A-HY',
    appId: '1:232668855467:android:a67494aa15d83853d18bee',
    messagingSenderId: '232668855467',
    projectId: 'jjpcparts',
    storageBucket: 'jjpcparts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-j2pWj7BVs323AtyXyv2BlafbuLHFQNA',
    appId: '1:232668855467:ios:14177548474fd6c2d18bee',
    messagingSenderId: '232668855467',
    projectId: 'jjpcparts',
    storageBucket: 'jjpcparts.appspot.com',
    iosBundleId: 'com.example.jjPcpartsProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-j2pWj7BVs323AtyXyv2BlafbuLHFQNA',
    appId: '1:232668855467:ios:14177548474fd6c2d18bee',
    messagingSenderId: '232668855467',
    projectId: 'jjpcparts',
    storageBucket: 'jjpcparts.appspot.com',
    iosBundleId: 'com.example.jjPcpartsProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArW-bEU1W32VoQw6JpQ7XXQl_kW01pGqM',
    appId: '1:232668855467:web:23963043143ea0f4d18bee',
    messagingSenderId: '232668855467',
    projectId: 'jjpcparts',
    authDomain: 'jjpcparts.firebaseapp.com',
    storageBucket: 'jjpcparts.appspot.com',
  );
}
